// <auto-generated />
using System;
using DmsAssignment.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DmsAssignment.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DmsAssignment.Domain.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquisitionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceCategoryId");

                    b.ToTable("Device");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcquisitionDate = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3759),
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3761),
                            DeviceCategoryId = 2,
                            IsDeleted = false,
                            Memo = "",
                            Name = "HP Desktop 1190",
                            SerialNo = "334cdh32-1"
                        });
                });

            modelBuilder.Entity("DmsAssignment.Domain.Entities.DeviceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3486),
                            IsDeleted = false,
                            Name = "Printer"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3540),
                            IsDeleted = false,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3544),
                            IsDeleted = false,
                            Name = "Switch"
                        });
                });

            modelBuilder.Entity("DmsAssignment.Domain.Entities.DeviceCategoryProperty", b =>
                {
                    b.Property<int>("DeviceCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("DeviceCategoryId", "PropertyId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("DeviceCategoryId", "PropertyId")
                        .IsUnique();

                    b.ToTable("DeviceCategoryProperty");

                    b.HasData(
                        new
                        {
                            DeviceCategoryId = 1,
                            PropertyId = 5,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3699),
                            Id = 0,
                            IsDeleted = false
                        },
                        new
                        {
                            DeviceCategoryId = 1,
                            PropertyId = 11,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3706),
                            Id = 0,
                            IsDeleted = false
                        },
                        new
                        {
                            DeviceCategoryId = 1,
                            PropertyId = 12,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3709),
                            Id = 0,
                            IsDeleted = false
                        },
                        new
                        {
                            DeviceCategoryId = 2,
                            PropertyId = 5,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3712),
                            Id = 0,
                            IsDeleted = false
                        },
                        new
                        {
                            DeviceCategoryId = 2,
                            PropertyId = 1,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3715),
                            Id = 0,
                            IsDeleted = false
                        },
                        new
                        {
                            DeviceCategoryId = 2,
                            PropertyId = 2,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3719),
                            Id = 0,
                            IsDeleted = false
                        },
                        new
                        {
                            DeviceCategoryId = 2,
                            PropertyId = 12,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3722),
                            Id = 0,
                            IsDeleted = false
                        },
                        new
                        {
                            DeviceCategoryId = 2,
                            PropertyId = 7,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3725),
                            Id = 0,
                            IsDeleted = false
                        },
                        new
                        {
                            DeviceCategoryId = 2,
                            PropertyId = 13,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3728),
                            Id = 0,
                            IsDeleted = false
                        },
                        new
                        {
                            DeviceCategoryId = 2,
                            PropertyId = 14,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3732),
                            Id = 0,
                            IsDeleted = false
                        },
                        new
                        {
                            DeviceCategoryId = 3,
                            PropertyId = 5,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3735),
                            Id = 0,
                            IsDeleted = false
                        },
                        new
                        {
                            DeviceCategoryId = 3,
                            PropertyId = 12,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3738),
                            Id = 0,
                            IsDeleted = false
                        },
                        new
                        {
                            DeviceCategoryId = 3,
                            PropertyId = 8,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3741),
                            Id = 0,
                            IsDeleted = false
                        },
                        new
                        {
                            DeviceCategoryId = 3,
                            PropertyId = 10,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3744),
                            Id = 0,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("DmsAssignment.Domain.Entities.DevicePropertyValue", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeviceId", "PropertyId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("DeviceId", "PropertyId")
                        .IsUnique();

                    b.ToTable("DevicePropertyValue");

                    b.HasData(
                        new
                        {
                            DeviceId = 1,
                            PropertyId = 2,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3777),
                            Id = 1,
                            IsDeleted = false,
                            Value = "Core I7"
                        },
                        new
                        {
                            DeviceId = 1,
                            PropertyId = 5,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3783),
                            Id = 2,
                            IsDeleted = false,
                            Value = "192.168.1.5"
                        },
                        new
                        {
                            DeviceId = 1,
                            PropertyId = 7,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3786),
                            Id = 3,
                            IsDeleted = false,
                            Value = "Mohamed Samy"
                        });
                });

            modelBuilder.Entity("DmsAssignment.Domain.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyTypeId");

                    b.ToTable("Property");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3587),
                            IsDeleted = false,
                            Name = "HD",
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3594),
                            IsDeleted = false,
                            Name = "Processor",
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3597),
                            IsDeleted = false,
                            Name = "Dimensions",
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3601),
                            IsDeleted = false,
                            Name = "MAC Address",
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3604),
                            IsDeleted = false,
                            Name = "IP Address",
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3609),
                            IsDeleted = false,
                            Name = "Allow USB",
                            PropertyTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3612),
                            IsDeleted = false,
                            Name = "Current User",
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3615),
                            IsDeleted = false,
                            Name = "Network Speed",
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3619),
                            IsDeleted = false,
                            Name = "Operating System",
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3667),
                            IsDeleted = false,
                            Name = "ports",
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3671),
                            IsDeleted = false,
                            Name = "Is Color",
                            PropertyTypeId = 2
                        },
                        new
                        {
                            Id = 12,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3674),
                            IsDeleted = false,
                            Name = "Brand",
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3677),
                            IsDeleted = false,
                            Name = "Display",
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3680),
                            IsDeleted = false,
                            Name = "Ram",
                            PropertyTypeId = 1
                        });
                });

            modelBuilder.Entity("DmsAssignment.Domain.Entities.PropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PropertyType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3561),
                            IsDeleted = false,
                            Name = "String",
                            PropertyId = 0
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 10, 25, 23, 7, 54, 99, DateTimeKind.Local).AddTicks(3568),
                            IsDeleted = false,
                            Name = "Boolean",
                            PropertyId = 0
                        });
                });

            modelBuilder.Entity("JobResearchSystem.Domain.Entities.Extend.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DmsAssignment.Domain.Entities.Device", b =>
                {
                    b.HasOne("DmsAssignment.Domain.Entities.DeviceCategory", "DeviceCategory")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceCategory");
                });

            modelBuilder.Entity("DmsAssignment.Domain.Entities.DeviceCategoryProperty", b =>
                {
                    b.HasOne("DmsAssignment.Domain.Entities.DeviceCategory", "DeviceCategory")
                        .WithMany("DeviceCategoryProperties")
                        .HasForeignKey("DeviceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DmsAssignment.Domain.Entities.Property", "Property")
                        .WithMany("DeviceCategoryProperties")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceCategory");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("DmsAssignment.Domain.Entities.DevicePropertyValue", b =>
                {
                    b.HasOne("DmsAssignment.Domain.Entities.Device", "Device")
                        .WithMany("DevicePropertyValues")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DmsAssignment.Domain.Entities.Property", "Property")
                        .WithMany("DevicePropertyValues")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("DmsAssignment.Domain.Entities.Property", b =>
                {
                    b.HasOne("DmsAssignment.Domain.Entities.PropertyType", "PropertyType")
                        .WithMany("Property")
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("JobResearchSystem.Domain.Entities.Extend.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("JobResearchSystem.Domain.Entities.Extend.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobResearchSystem.Domain.Entities.Extend.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("JobResearchSystem.Domain.Entities.Extend.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DmsAssignment.Domain.Entities.Device", b =>
                {
                    b.Navigation("DevicePropertyValues");
                });

            modelBuilder.Entity("DmsAssignment.Domain.Entities.DeviceCategory", b =>
                {
                    b.Navigation("DeviceCategoryProperties");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("DmsAssignment.Domain.Entities.Property", b =>
                {
                    b.Navigation("DeviceCategoryProperties");

                    b.Navigation("DevicePropertyValues");
                });

            modelBuilder.Entity("DmsAssignment.Domain.Entities.PropertyType", b =>
                {
                    b.Navigation("Property");
                });
#pragma warning restore 612, 618
        }
    }
}
